[theme]
base = "light"
primaryColor = "#E4EFE7"
backgroundColor = "#FAF1E6"
secondaryBackgroundColor = "#FDFAF6"
textColor = "#064420"
font = "sans serif"

## https://colorhunt.co/palette/faf1e6fdfaf6e4efe7064420